import java.util.concurrent.atomic.AtomicBoolean;


public class LessonePanel extends javax.swing.JPanel {

    /**
     * Creates new form Lessonpanel
     */
    public LessonePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        deslabel = new javax.swing.JLabel();
        alphalabel = new javax.swing.JLabel();
        imglabel = new javax.swing.JLabel();
        gob = new javax.swing.JButton();
        final AtomicBoolean lock2 = new AtomicBoolean(false);
        final AtomicBoolean lock3 = new AtomicBoolean(false);

        setBackground(new java.awt.Color(51, 255, 204));

        deslabel.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        deslabel.setForeground(new java.awt.Color(0, 0, 204));
        deslabel.setText("E FOR EGG");

        alphalabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("e.png"))); // NOI18N

        imglabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("Egg.jpg"))); // NOI18N

        gob.setBackground(new java.awt.Color(255, 255, 0));
        gob.setForeground(new java.awt.Color(0, 0, 204));
        gob.setText("Go for C");
        gob.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(imglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(alphalabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deslabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                       // .addComponent(gob, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        //.addComponent(gob, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(alphalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(imglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
    }// </editor-fold>

    


    // Variables declaration - do not modify                     
    private javax.swing.JLabel alphalabel;
    private javax.swing.JLabel deslabel;
    public javax.swing.JButton gob;
    private javax.swing.JLabel imglabel;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration                   
}
