

import java.util.List;

import javax.persistence.*;



/**
 *
 * @author Sony
 */
public class TopScorePanel extends javax.swing.JPanel {

    /**
     * Creates new form TopscorePanel
     */
    public TopScorePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	setOpaque(false);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        topScorersLabel = new javax.swing.JLabel();
        topScoreLabel = new javax.swing.JLabel();
        topScoreTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        back10 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBackground(new java.awt.Color(51, 255, 204));
        jScrollPane1.setViewportView(jTextArea1);

        
        topScoreTextField.setBackground(new java.awt.Color(51, 255, 204));
        
        topScorersLabel.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        topScorersLabel.setForeground(new java.awt.Color(0, 51, 255));
        topScorersLabel.setText("          STUDENTS WITH TOP SCORE");
        topScorersLabel.setBorder(new javax.swing.border.MatteBorder(null));

        topScoreLabel.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        topScoreLabel.setForeground(new java.awt.Color(0, 51, 255));
        topScoreLabel.setText("TOP SCORE:");

        jTextArea2.setColumns(20);
        jTextArea2.setBackground(new java.awt.Color(51, 255, 204));
        jTextArea2.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("PersistenceUnit");
    	EntityManager manager = emf.createEntityManager();
    	EntityTransaction transaction = manager.getTransaction();

    	transaction.begin();
		TypedQuery<Object []> query1 = manager.createQuery("SELECT e.student_name, e.score FROM student e where e.score in (SELECT max(e.score) from student e)", Object[].class);
    	List<Object []> result1 = query1.getResultList();
		for (Object[] data : result1){
			topScoreTextField.setText(String.valueOf(data[1]));
			jTextArea2.append(String.valueOf(data[0]));
			jTextArea2.append("\n");

        back10.setBackground(new java.awt.Color(204, 204, 255));
        back10.setFont(new java.awt.Font("Aharoni", 1, 10)); // NOI18N
        back10.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back10)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(topScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(topScoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(topScorersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(back10)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topScoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topScoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addComponent(topScorersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>                        
    }

    // Variables declaration - do not modify                     
    public javax.swing.JButton back10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel topScoreLabel;
    private javax.swing.JTextField topScoreTextField;
    private javax.swing.JLabel topScorersLabel;
    // End of variables declaration                   
}

   
    	
 
